name: Frontend CI

on:
  pull_request:
    branches: [ "dev" ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"

env:
  WORKING_DIRECTORY: frontend

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Build frontend
        run: npm run build
        working-directory: ${{ env.WORKING_DIRECTORY }}
